<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SteamShuffle.ApiClients\SteamShuffle.ApiClients.csproj" />
    <ProjectReference Include="..\SteamShuffle.CoreModels\SteamShuffle.CoreModels.csproj" />
  </ItemGroup>

</Project>
